"""initial schema

Revision ID: 09bf0f95d05e
Revises: 
Create Date: 2026-06-12 22:04:24.962508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bf0f95d05e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('primary_field', sa.String(), nullable=True),
    sa.Column('scholar_url', sa.Text(), nullable=True),
    sa.Column('scholar_source', sa.String(), nullable=True),
    sa.Column('total_publications', sa.Integer(), nullable=False),
    sa.Column('um_publications', sa.Integer(), nullable=False),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=False),
    sa.Column('i10_index', sa.Integer(), nullable=False),
    sa.Column('shuffle_key', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_authors_shuffle', 'authors', ['shuffle_key'], unique=False)
    op.create_table('collaborations_countries',
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('collaborations_institutions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('dataset_meta',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('departments',
    sa.Column('name_norm', sa.String(), nullable=False),
    sa.Column('name_display', sa.Text(), nullable=False),
    sa.Column('publication_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name_norm')
    )
    op.create_table('fields',
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('field_name')
    )
    op.create_table('grant_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_grants', sa.Integer(), nullable=False),
    sa.Column('total_funding_usd', sa.Float(), nullable=False),
    sa.Column('top_funder', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grants_by_funder',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ingest_checkpoint',
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_completed_key', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stage')
    )
    op.create_table('institution_overview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=False),
    sa.Column('cited_by_count', sa.BigInteger(), nullable=False),
    sa.Column('h_index', sa.Integer(), nullable=False),
    sa.Column('i10_index', sa.Integer(), nullable=False),
    sa.Column('open_access_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_counts',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('oa_by_year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('oa_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('oa_status_counts',
    sa.Column('oa_status', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('oa_status')
    )
    op.create_table('publications_by_year',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year', 'source')
    )
    op.create_table('referenced_work_venues',
    sa.Column('referenced_work_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=False),
    sa.Column('oa_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('referenced_work_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_repository_or_index', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_counts',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('author_citation_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('is_oa', sa.Boolean(), nullable=False),
    sa.Column('oa_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citsrc_author', 'author_citation_sources', ['author_id'], unique=False)
    op.create_table('author_expertise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expertise_author', 'author_expertise', ['author_id'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_norm', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('oa_status', sa.String(), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('primary_source_id', sa.String(), nullable=True),
    sa.Column('is_duplicate_of', sa.String(), nullable=True),
    sa.Column('excluded_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['works.id'], ),
    sa.ForeignKeyConstraint(['primary_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_works_canonical', 'works', ['is_duplicate_of', 'excluded_reason'], unique=False)
    op.create_index('ix_works_doi', 'works', ['doi'], unique=False)
    op.create_index('ix_works_title_norm', 'works', ['title_norm'], unique=False)
    op.create_index('ix_works_type', 'works', ['type'], unique=False)
    op.create_index('ix_works_year', 'works', ['year'], unique=False)
    op.create_table('author_works',
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'work_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author_works')
    op.drop_index('ix_works_year', table_name='works')
    op.drop_index('ix_works_type', table_name='works')
    op.drop_index('ix_works_title_norm', table_name='works')
    op.drop_index('ix_works_doi', table_name='works')
    op.drop_index('ix_works_canonical', table_name='works')
    op.drop_table('works')
    op.drop_index('ix_expertise_author', table_name='author_expertise')
    op.drop_table('author_expertise')
    op.drop_index('ix_citsrc_author', table_name='author_citation_sources')
    op.drop_table('author_citation_sources')
    op.drop_table('type_counts')
    op.drop_table('sources')
    op.drop_table('referenced_work_venues')
    op.drop_table('publications_by_year')
    op.drop_table('oa_status_counts')
    op.drop_table('oa_by_year')
    op.drop_table('journal_counts')
    op.drop_table('institution_overview')
    op.drop_table('ingest_checkpoint')
    op.drop_table('grants_by_funder')
    op.drop_table('grant_summary')
    op.drop_table('fields')
    op.drop_table('departments')
    op.drop_table('dataset_meta')
    op.drop_table('collaborations_institutions')
    op.drop_table('collaborations_countries')
    op.drop_index('ix_authors_shuffle', table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
